services:
  testtask.api:
    image: ${DOCKER_REGISTRY-}testtaskapi
    build:
      context: .
      dockerfile: TestTask.Api/Dockerfile
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - postgres_volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
    - 15432:80
    volumes:
    - pgadmin_volume:/var/lib/pgadmin
    depends_on:
    - db

volumes:
  postgres_volume:
  pgadmin_volume: